#!/usr/bin/with-contenv bash
set -x

cd /local

if [ -z "${ENABLE_WEB}" ]; then
  /usr/bin/rclone rcd \
    --fast-list \
    --rc-web-gui-no-open-browser \
    --rc-no-auth
else
  /usr/bin/rclone rcd \
    --fast-list \
    --rc-web-gui \
    --rc-web-fetch-url <rc-web-url> \
    --rc-web-gui-update \
    --rc-user <rc-user> \
    --rc-pass <rc-pass> \
    --rc-addr :5572 \
    --rc-web-gui-no-open-browser
fi