#!/usr/bin/with-contenv bash

/usr/bin/rclone mount \
  --config=/config/rclone.conf \
  --log-level=INFO \
  --log-file=/var/log/rclone/rclone-mount.log \
  --user-agent=rclonemediadrive \
  --umask=002 \
  --gid=100 \
  --uid=1001 \
  --allow-other \
  --timeout=1h \
  --poll-interval=15s \
  --dir-cache-time=1000h \
  --cache-dir=/local-cache \
  --vfs-cache-mode=full \
  --vfs-cache-max-size=<cache-size> \
  --vfs-cache-max-age=<cache-time> \
  <gdrive-rclone>: /gdrive-cloud